[package]
name = "chip8"
version = "0.1.0"
edition = "2021"
description = "A CHIP-8 interpreter written in Rust"
license = "MIT"
repository = "https://github.com/dixslyf/chip8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.30.12"
pixels = "0.15.0"
log = "0.4.17"
fern = { version = "0.7.1", features = ["colored"] }
clap = { version = "4.0.18", features = ["derive"] }
arrayvec = "0.7.2"
bitvec = "1.0.1"
rand = "0.9.2"
rodio = "0.21.1"

[dev-dependencies]
proptest = "1.8.0"
